appUrl=https://automationintesting.online/
browser=Chrome
webDriver=chromedriver
driverVersion=132
webDriverWaitTime=20
implicitlyWaitTime=5
testCasePass=_PASS
testCaseFail=_FAIL
testCaseSkipped=_SKIPPED
reportPath=/test-output/report/
screenShotFolderPath=/src/test/resource/screenshots/
fileFormat=.png
testDataPath=/src/test/resource/data/TestData.xlsx
execPath=/exec/